### ISSUE TITLE
When running plugin I get errors

### ISSUE THREAD

**Issue by arogl** [mschuerig/beets-top#1]
Hi,

With my limited python knowledge I get the following error on windows:

e:>beet top artists
    'template': template,
UnboundLocalError: local variable 'template' referenced before assignment

I think template is never set, so I dded the following lines and that seems to have fixed it:

Line 50:
    "artist":  Template("$subject"),
    "albumartist":  Template("$subject"),
    "composer":  Template("$subject"),
    "format":  Template("$subject"),
    "genre":  Template("$subject"),
    "label":  Template("$subject"),
    "year":  Template("$subject"),

Line 95:
        template = TEMPLATES.get(subject)

Hope you understand,
Andrew

**Comment by mschuerig** [comment]
Thanks, I've added the missing templates.
